name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sitkoru/actions-container
    env:
      PROJECT: Sitko.Blazor.ScriptInjector
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Install node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '15'
      - name: Build js
        working-directory: src/${{ env.PROJECT }}/Web
        shell: bash
        run: |
          npm ci
          npm run prod
      - name: Install .NET Core 3.1
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 5.0.x
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '5.0.x'
      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Create package
        run: dotnet pack -c Release src/${{ env.PROJECT}}
