name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sitkoru/actions-container
    env:
      PROJECT: Sitko.Blazor.ScriptInjector
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build js
        working-directory: src/${{ env.PROJECT }}/Web
        shell: bash
        run: |
          npm ci
          npm run prod
      - name: Create package
        run: dotnet pack -c Release src/${{ env.PROJECT}}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Semantic Release
        uses: sitkoru/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.BOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.BOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.BOT_EMAIL }}
